Repository pareek-narendra/pkce, pull requests merged in 2020-10, with the labels that each got.

#9 added golang hash algorithm for SHA1, SHA256, SHA512, MD5
  Golang/algorithm.go
Labels: In Review

#12 Update NodeJs Document.md
  Golang/Document.md
  NodeJs/Document.md
Labels: Ready for Merge

#16 Update Readme.md
  README.md
Labels: hacktoberfest-accepted

#18 Update README
  README.md
Labels: hacktoberfest-accepted
